Migrate linux prebuild images to docker
CI/CD:
build: updated gcc reference versions for ci
build: added image definitions for build steps when using linux
build: updated package installing to not use sudo or rework to use apk for alpine contexts

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -11,8 +11,8 @@ variables:
   VULKAN_VERSION: 1.3.275.0
   C_CLANG_TARGET: clang-18
   CXX_CLANG_TARGET: clang++-18
-  C_GCC_TARGET: gcc-13
-  CXX_GCC_TARGET: g++-13
+  C_GCC_TARGET: gcc-14
+  CXX_GCC_TARGET: g++-14
 
 stages:
   - build
@@ -157,6 +157,7 @@ build.windows.clang:
       dotenv: build.report.env
 
 build.linux.gcc:
+  image: docker.io/gcc:14.2.0-bookworm
   stage: build
   tags:
     - linux
@@ -165,19 +166,19 @@ build.linux.gcc:
   # Preparation
   before_script:
     # Prepare Commands
-    - command -v make 2>&1 || { echo >&2 "Required unavailable command make, try to recover."; sudo apt-get install build-essential -y; }
-    - command -v cmake 2>&1 || { echo >&2 "Required unavailable command cmake, try to recover."; sudo apt-get install cmake -y; }
-    - command -v g++ 2>&1 || { echo >&2 "Required unavailable command g++, try to recover."; sudo apt-get install build-essential -y; }
-    - command -v xz 2>&1 || { echo >&2 "Required unavailable command xz, try to recover."; sudo apt-get install xz-utils -y; }
+    - apt-get update
+    - command -v git 2>&1 || { echo >&2 "Required unavailable command git, try to recover."; apt-get -qq install git git-lfs -y; }
+    - command -v cmake 2>&1 || { echo >&2 "Required unavailable command cmake, try to recover."; apt-get -qq install cmake -y; }
+    - command -v xz 2>&1 || { echo >&2 "Required unavailable command xz, try to recover."; apt-get -qq install xz-utils -y; }
     # Optional Commands
-    - command -v ninja 2>&1 || { echo >&2 "Optional unavailable command ninja, try to recover."; sudo apt-get install ninja-build -y; }
+    - command -v ninja 2>&1 || { echo >&2 "Optional unavailable command ninja, try to recover."; apt-get -qq install ninja-build -y; }
     # Check Versions
     - cmake --version
     # Install System Dependencies
-    - sudo apt-get -qq install pkg-config cmake-data mesa-vulkan-drivers -y
-    - sudo apt-get -qq install xcb libx11-xcb1 libxcb1-dev libxcb-xfixes0 libxcb-xfixes0-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxcursor1 libxcursor-dev libxrandr2 libxrandr-dev libxrender1 libxrender-dev libxss1 libxss-dev libxi6 x11proto-dev xorg-sgml-doctools libxi-dev -y
-    - sudo apt-get -qq install libwayland-dev libwayland-client0 libwayland-cursor0 libegl1-mesa-dev libegl-mesa0 libwayland-egl-backend-dev libwayland-egl1 libxkbcommon-dev libxkbcommon0 libdecor-0-dev libdecor-0-0 -y
-    - sudo apt-get -qq install libuuid1 uuid-dev -y
+    - apt-get -qq install pkg-config cmake-data mesa-vulkan-drivers -y
+    - apt-get -qq install xcb libx11-xcb1 libxcb1-dev libxcb-xfixes0 libxcb-xfixes0-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxcursor1 libxcursor-dev libxrandr2 libxrandr-dev libxrender1 libxrender-dev libxss1 libxss-dev libxi6 x11proto-dev xorg-sgml-doctools libxi-dev -y
+    - apt-get -qq install libwayland-dev libwayland-client0 libwayland-cursor0 libegl1-mesa-dev libegl-mesa0 libwayland-egl-backend-dev libwayland-egl1 libxkbcommon-dev libxkbcommon0 libdecor-0-dev libdecor-0-0 -y
+    - apt-get -qq install libuuid1 uuid-dev -y
 
   # Process
   script:
@@ -218,6 +219,7 @@ build.linux.gcc:
       dotenv: build.report.env
 
 build.linux.clang:
+  image: docker.io/silkeh/clang:18-bookworm
   stage: build
   tags:
     - linux
@@ -226,24 +228,17 @@ build.linux.clang:
   # Preparation
   before_script:
     # Prepare Commands
-    - command -v make 2>&1 || { echo >&2 "Required unavailable command make, try to recover."; sudo apt-get install build-essential -y; }
-    - command -v cmake 2>&1 || { echo >&2 "Required unavailable command cmake, try to recover."; sudo apt-get install cmake -y; }
-    - |-
-      command -v $C_CLANG_TARGET 2>&1 || {
-          echo >&2 "Required unavailable command clang, try to recover."
-          sudo apt-get install lsb-release wget software-properties-common gnupg -y
-          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
-      }
-    - command -v xz 2>&1 || { echo >&2 "Required unavailable command xz, try to recover."; sudo apt-get install xz-utils -y; }
+    - apt-get update
+    - command -v git 2>&1 || { echo >&2 "Required unavailable command git, try to recover."; apt-get -qq install git git-lfs -y; }
+    - command -v cmake 2>&1 || { echo >&2 "Required unavailable command cmake, try to recover."; apt-get -qq install cmake -y; }
+    - command -v xz 2>&1 || { echo >&2 "Required unavailable command xz, try to recover."; apt-get -qq install xz-utils -y; }
     # Optional Commands
-    - command -v ninja 2>&1 || { echo >&2 "Optional unavailable command ninja, try to recover."; sudo apt-get install ninja-build -y; }
-    # Check Versions
-    - cmake --version
+    - command -v ninja 2>&1 || { echo >&2 "Optional unavailable command ninja, try to recover."; apt-get -qq install ninja-build -y; }
     # Install System Dependencies
-    - sudo apt-get -qq install pkg-config cmake-data mesa-vulkan-drivers -y
-    - sudo apt-get -qq install xcb libx11-xcb1 libxcb1-dev libxcb-xfixes0 libxcb-xfixes0-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxcursor1 libxcursor-dev libxrandr2 libxrandr-dev libxrender1 libxrender-dev libxss1 libxss-dev libxi6 x11proto-dev xorg-sgml-doctools libxi-dev -y
-    - sudo apt-get -qq install libwayland-dev libwayland-client0 libwayland-cursor0 libegl1-mesa-dev libegl-mesa0 libwayland-egl-backend-dev libwayland-egl1 libxkbcommon-dev libxkbcommon0 libdecor-0-dev libdecor-0-0 -y
-    - sudo apt-get -qq install libuuid1 uuid-dev -y
+    - apt-get -qq install pkg-config cmake-data mesa-vulkan-drivers -y
+    - apt-get -qq install xcb libx11-xcb1 libxcb1-dev libxcb-xfixes0 libxcb-xfixes0-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxcursor1 libxcursor-dev libxrandr2 libxrandr-dev libxrender1 libxrender-dev libxss1 libxss-dev libxi6 x11proto-dev xorg-sgml-doctools libxi-dev -y
+    - apt-get -qq install libwayland-dev libwayland-client0 libwayland-cursor0 libegl1-mesa-dev libegl-mesa0 libwayland-egl-backend-dev libwayland-egl1 libxkbcommon-dev libxkbcommon0 libdecor-0-dev libdecor-0-0 -y
+    - apt-get -qq install libuuid1 uuid-dev -y
 
   # Process
   script:
@@ -252,7 +247,7 @@ build.linux.clang:
     # Generator: Makefiles ~ '-A x64' by default
 
     # CMake - Debug
-    - cmake -S . -B build/Debug -D CMAKE_C_COMPILER=`which $C_CLANG_TARGET` -D CMAKE_CXX_COMPILER=`which $CXX_CLANG_TARGET` -D CMAKE_BUILD_TYPE=Debug
+    - cmake -S . -B build/Debug -D CMAKE_C_COMPILER=`which $C_CLANG_TARGET` -D CMAKE_CXX_COMPILER=`which $CXX_CLANG_TARGET` -D CMAKE_CXX_FLAGS=-stdlib=libc++ -D CMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ -D CMAKE_BUILD_TYPE=Debug
     - cmake --build build/Debug -t Heliogrim-Heliogrim --parallel $(nproc)
     - cmake --build build/Debug -t Heliogrim-Editor --parallel $(nproc)
     - cmake --build build/Debug -t Heliogrim-AllTests --parallel $(nproc)
@@ -344,6 +339,7 @@ test.windows.clang:
       junit: ctest-report.xml
 
 test.linux.gcc:
+  image: docker.io/alpine:3.20.2
   stage: test
   tags:
     - linux
@@ -354,20 +350,18 @@ test.linux.gcc:
 
   # Preparation
   before_script:
-    - cmake --version
-    - $logical_core_count = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
     # Install System Dependencies
-    - sudo apt-get -qq install pkg-config cmake-data mesa-vulkan-drivers -y
-    - sudo apt-get -qq install xcb libx11-xcb1 libxcb1-dev libxcb-xfixes0 libxcb-xfixes0-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxcursor1 libxcursor-dev libxrandr2 libxrandr-dev libxrender1 libxrender-dev libxss1 libxss-dev libxi6 x11proto-dev xorg-sgml-doctools libxi-dev -y
-    - sudo apt-get -qq install libwayland-dev libwayland-client0 libwayland-cursor0 libegl1-mesa-dev libegl-mesa0 libwayland-egl-backend-dev libwayland-egl1 libxkbcommon-dev libxkbcommon0 libdecor-0-dev libdecor-0-0 -y
-    - sudo apt-get -qq install libuuid1 uuid-dev -y
+    - apk add --no-cache pkgconf cmake mesa git git-lfs
+    - apk add --no-cache libx11 libx11-dev libxcursor libxcursor-dev libxfixes libxfixes-dev libxext libxext-dev libxrandr libxrandr-dev libxrender libxrender-dev libxi libxi-dev
+    - apk add --no-cache wayland libdecor libdecor-dev xkbcli
+    - apk add --no-cache libuuid ossp-uuid-dev
 
   # Process
   script:
     # Testing
 
     # CMake - Debug
-    - ctest --test-dir build/Debug --output-junit "$PWD/ctest-report.xml" --parallel $logical_core_count
+    - ctest --test-dir build/Debug --output-junit "$PWD/ctest-report.xml" --parallel $(nproc)
 
   artifacts:
     when: always
@@ -377,6 +371,7 @@ test.linux.gcc:
       junit: ctest-report.xml
 
 test.linux.clang:
+  image: docker.io/alpine:3.20.2
   stage: test
   tags:
     - linux
@@ -387,20 +382,18 @@ test.linux.clang:
 
   # Preparation
   before_script:
-    - cmake --version
-    - $logical_core_count = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
     # Install System Dependencies
-    - sudo apt-get -qq install pkg-config cmake-data mesa-vulkan-drivers -y
-    - sudo apt-get -qq install xcb libx11-xcb1 libxcb1-dev libxcb-xfixes0 libxcb-xfixes0-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxcursor1 libxcursor-dev libxrandr2 libxrandr-dev libxrender1 libxrender-dev libxss1 libxss-dev libxi6 x11proto-dev xorg-sgml-doctools libxi-dev -y
-    - sudo apt-get -qq install libwayland-dev libwayland-client0 libwayland-cursor0 libegl1-mesa-dev libegl-mesa0 libwayland-egl-backend-dev libwayland-egl1 libxkbcommon-dev libxkbcommon0 libdecor-0-dev libdecor-0-0 -y
-    - sudo apt-get -qq install libuuid1 uuid-dev -y
+    - apk add --no-cache pkgconf cmake mesa git git-lfs
+    - apk add --no-cache libx11 libx11-dev libxcursor libxcursor-dev libxfixes libxfixes-dev libxext libxext-dev libxrandr libxrandr-dev libxrender libxrender-dev libxi libxi-dev
+    - apk add --no-cache wayland libdecor libdecor-dev xkbcli
+    - apk add --no-cache libuuid ossp-uuid-dev
 
   # Process
   script:
     # Testing
 
     # CMake - Debug
-    - ctest --test-dir build/Debug --output-junit "$PWD/ctest-report.xml" --parallel $logical_core_count
+    - ctest --test-dir build/Debug --output-junit "$PWD/ctest-report.xml" --parallel $(nproc)
 
   artifacts:
     when: always
@@ -412,6 +405,7 @@ test.linux.clang:
 # Release / Deployment Section
 
 release:
+  image: docker.io/alpine:3.20.2
   stage: release
   tags:
     - linux
@@ -429,15 +423,16 @@ release:
       artifacts: true
   before_script:
     # Prepare Commands
+    - apk add --no-cache curl wget tar xz unzip glab git git-lfs
     - |-
       command -v release-cli 2>&1 || {
           echo >&2 "Required unavailable command release-cli, try to recover."
-          wget https://go.dev/dl/go1.20.5.linux-amd64.tar.gz
-          sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.20.5.linux-amd64.tar.gz
+          wget https://go.dev/dl/go1.23.0.linux-amd64.tar.gz
+          rm -rf /usr/local/go && tar -C /usr/local -xzf go1.23.0.linux-amd64.tar.gz
           export PATH=$PATH:/usr/local/go/bin
           source ~/.bashrc
-          sudo curl --location --output /usr/local/bin/release-cli "https://gitlab.com/api/v4/projects/gitlab-org%2Frelease-cli/packages/generic/release-cli/latest/release-cli-linux-amd64"
-          sudo chmod +x /usr/local/bin/release-cli
+          curl --location --output /usr/local/bin/release-cli "https://gitlab.com/api/v4/projects/gitlab-org%2Frelease-cli/packages/generic/release-cli/latest/release-cli-linux-amd64"
+          chmod +x /usr/local/bin/release-cli
           source ~/.bashrc
       }
   script:
